# Generated by Django 5.0.6 on 2025-05-28 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(blank=True, max_length=255, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('prematuro', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True)),
                ('semanasCorrigidas', models.IntegerField(blank=True, null=True)),
                ('diasCorrigidos', models.IntegerField(blank=True, null=True)),
                ('sexo', models.TextField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro')], max_length=10, null=True)),
                ('tipo_sanguineo', models.CharField(blank=True, choices=[('a+', 'A+'), ('a-', 'A-'), ('ab+', 'AB+'), ('ab-', 'AB-'), ('b+', 'B+'), ('b-', 'B-'), ('o+', 'O+'), ('o-', 'O-')], max_length=10, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf_responsavel', models.CharField(blank=True, default='', max_length=14, null=True)),
                ('rg_responsavel', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NovaConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('dataConsulta', models.DateField()),
                ('idade', models.CharField(blank=True, max_length=50, null=True)),
                ('idadeMeses', models.IntegerField(blank=True, null=True)),
                ('doencaPrevia', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True)),
                ('especificacaoDoencaPrevia', models.TextField(blank=True, null=True)),
                ('medicamentoUso', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True)),
                ('especificacaoMedicamentoUso', models.TextField(blank=True, null=True)),
                ('historicoGestacional', models.TextField(blank=True, null=True)),
                ('anamnese', models.TextField(blank=True, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('estatura', models.FloatField(blank=True, null=True)),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('perimetroCefalico', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('testeReflexoVermelho', models.TextField(blank=True, null=True)),
                ('auscultaCardiaca', models.TextField(blank=True, null=True)),
                ('frequenciaCardiaca', models.IntegerField(blank=True, null=True)),
                ('pressaoArterial', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('auscultaPulmonar', models.TextField(blank=True, null=True)),
                ('frequenciaRespiratoria', models.IntegerField(blank=True, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('oroscopia', models.TextField(blank=True, null=True)),
                ('otoscopia', models.TextField(blank=True, null=True)),
                ('exameAbdominal', models.TextField(blank=True, null=True)),
                ('genituPelve', models.TextField(blank=True, null=True)),
                ('tanner', models.TextField(blank=True, null=True)),
                ('membrosInferiores', models.TextField(blank=True, null=True)),
                ('pele', models.TextField(blank=True, null=True)),
                ('outrosExames', models.TextField(blank=True, null=True)),
                ('avaliacao', models.TextField(blank=True, null=True)),
                ('cid', models.CharField(blank=True, max_length=20, null=True)),
                ('planoConduta', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cadastro')),
            ],
        ),
    ]
