# Generated by Django 5.0.6 on 2025-05-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novaconsulta',
            name='idadeCorrigida',
            field=models.TextField(blank=True, null=True),
        ),
    ]
