# Generated by Django 5.0.6 on 2025-07-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cadastro_nome_alter_cadastro_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='prematuro',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=5, null=True),
        ),
    ]
