# Generated by Django 5.0.6 on 2025-09-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cadastro_prematuro'),
    ]

    operations = [
        migrations.AddField(
            model_name='novaconsulta',
            name='avaliacaoEstatura',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='novaconsulta',
            name='avaliacaoPeso',
            field=models.TextField(blank=True, null=True),
        ),
    ]
