# Generated by Django 5.0.6 on 2025-09-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_novaconsulta_avaliacaoestatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novaconsulta',
            name='pressaoArterial',
            field=models.TextField(blank=True, null=True),
        ),
    ]
