# Generated by Django 5.0.6 on 2025-09-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_novaconsulta_pressaoarterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novaconsulta',
            name='fundoscopia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
