# Generated by Django 5.0.6 on 2025-09-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_novaconsulta_fundoscopia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novaconsulta',
            name='fundoscopia',
        ),
    ]
